#!/bin/sh
# Aliases and functions for interactive use.

## MAIN {{{

# Are you sure?
alias rm='rm -i'
alias cp='cp -vi'
alias mv='mv -i'

# Helpers/replacers
alias mkdir="mkdir -p"

command -v eza > /dev/null && {
    alias ls='eza -lh --group-directories-first'
    alias lt='eza --tree --level=2 --long --git'
    alias lta='lt -a'
}
command -v fzf >/dev/null && alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

# Coloring
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

## }}}

## FUNCTIONS {{{

# sponge command that doesn't require installing moreutils
sponge() {
    temp=$(mktemp) || { echo "mktemp: failed to create temp file" >&2; return 1; }
    trap 'rm -f "$temp"' EXIT
    cat > "$temp"

    if [ "$#" -eq 0 ]; then
        cat "$temp"
    else
        cat "$temp" > "$1"
    fi

    rm -f "$temp"
}

mime() {
    file -b --mime-type "$@"
}

# Use neovim if available
command -v nvim > /dev/null && {
    alias vim='nvim'
    n() {
        if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi
    }
}

## }}}

## ALIASES {{

# Convenience
alias roll="dice eval"

# Annoyance
alias mastoctl="madonctl"

# Kitty TERM
alias ssh="TERM=xterm ssh"

## }}}

# vim: set ft=bash et sw=4 ts=4 sts=4 fdm=marker:
