#!/usr/bin/env sh

set -e

[[ $(pgrep -cx brm_bar) > 1 ]] && exit 1

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# get screen size
IFS='x' read w h <<< "$(xrandr | awk '/\*/ {print $1}')"

. bar-config

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c $(dirname $0)/bar-conky > "$PANEL_FIFO" &

#while :; do
#    mkbar # cat a basic shell script
#done \
cat "$PANEL_FIFO" \
    | fifo2bar \
    | lemonbar \
        -f "$FONT2"\
        -F "$COLOR_FG"\
        -B "$COLOR_BG"\
        -g "$PANEL_GEOMETRY"\
        -u "$LINEHEIGHT" &
wait

