#! /bin/sh

bspc desktop -n 0

bspc config split_ratio             0.4
bspc config border_width            5
bspc config window_gap              20

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config auto_cancel             true

## COLORS {{{
    bspc config normal_border_color     '#1d1f21'
    #bspc config focused_border_color    '#373b41'
    bspc config focused_border_color    '#c5c8c6'
    bspc config active_border_color     '#1d1f21'
    bspc config presel_border_color     '#ffffff'
    bspc config urgent_border_color     '#cc342b'
    bspc config focused_private_border_color '#3971ed'
## }}}

## RULES {{{ 
    bspc rule -a lxappearance floating=on manage=on
    bspc rule -a MPlayer floating=on manage=on
    bspc rule -a Steam floating=on manage=on
    bspc rule -a Wfica private=on manage=on
## }}}

# Create/name desktops
case $HOSTNAME in
    "ax-l")
        #bspc monitor DVI-D-0 -d 0 1
        bspc monitor HDMI-0 -d 0 1
        bspc monitor DVI-I-1 -d 2 3
        ;;
    "ken-th")
        bspc monitor -d 0 1
        ;;
    "ad-ll")
        bspc monitor -d 0 1 2 3
esac

# vim: set et sts=4 ts=4 sw=4 fdm=marker:
