#! /bin/sh

# DESKTOP ICONS
# ◆◇■□

# source color vars
. /home/t/.vars_master

while read -r line ; do
	case $line in
		S*)
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_BG}${line#?}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_BG}${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}	# ie. "iix"
				case $item in
					O*)
						# active desktop
						wm_infos="$wm_infos%{F$COLOR_FOCUSED_FG}%{B$COLOR_BG} ■ "
						;;
					F*)
						# active empty desktop
						wm_infos="$wm_infos%{F$COLOR_FOCUSED_FG}%{B$COLOR_BG} □ "
						;;
					U*)
						# active urgent desktop
						wm_infos="$wm_infos%{F$COLOR_URGENT_FG}%{B$COLOR_BG} ■ "
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos%{F$COLOR_OCCUPIED_FG}%{B$COLOR_BG} ■ "
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos%{F$COLOR_FREE_FG}%{B$COLOR_BG} □ "
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos%{F$COLOR_URGENT_FG}%{B$COLOR_BG} ■ "
						;;
					L*)
						# layout
						# case $name in
						# 	t*)
						# 		layout="  "
						# 		;;
						# 	m*)
						# 		layout="  "
						# 		;;
						# esac
						# wm_infos="$layout$wm_infos"
						# ;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$title %{c} $wm_infos %{F$COLOR_BG}%{r} $sys_infos"
done
