#!/bin/sh
# ICON
# 
TEMP=`nvidia-settings -q GPUCoreTemp | grep 'ax-l:0.0' | cut -d' ' -f6 | sed 's/\.//'`
USE=`nvidia-settings -q GPUUtilization | grep 'ax-l:0' | cut -d' ' -f6 | sed 's/graphics=//' | sed 's/,//'`

OPTIND=1
while getopts "ftu" arg; do
case $arg in
	f) TEMP=`echo $TEMP*9/5+32 | bc`;;
	t) echo "$TEMP°";;
	u) echo "$USE";;
esac;done

