#!/bin/sh

# ICONS
# ⭩ ⭪ ⭫ ⭨ ±

STATE=$(acpi --battery | cut -d' ' -f3 | sed 's/,//')
VALUE=$(acpi --battery | cut -d' ' -f4 | sed 's/%,//')
SIGN=
ICON=

if [ "$VALUE" -gt 69 ]; then
	ICON=""
elif [ "$VALUE" -gt 39 ] && [ "$VALUE" -lt 70 ]; then
	ICON=""
elif [ "$VALUE" -gt 9 ] && [ "$VALUE" -lt 40 ]; then
	ICON=""
else
	ICON=""
fi

if [ "$STATE" == "Full" -o "$VALUE" == "100" ]; then
	ICON=""
	SIGN="±"
elif [ "$STATE" == "Charging" ]; then
	SIGN="+"
elif [ "$STATE" == "Discharging" ]; then
	SIGN="-"
else
	SIGN="±"
fi

echo $ICON $VALUE$SIGN
