#!/bin/sh

# ICONS
# ⭩ ⭪ ⭫ ⭨ ±

STATE=$(acpi --battery | cut -d' ' -f3 | sed 's/,//')
VALUE=$(acpi --battery | cut -d' ' -f4 | sed 's/%,//')
SIGN=
ICON=
NUMERIC="no"

OPTIND=1
while getopts "nh" arg; do
case $arg in
    h) echo -e "Usage: $(basename $0) [OPTION]..."
        echo -e "Battery status panel script.\n"
        echo -e " -n \tnumeric only (no symbols)"
        echo -e " -h \thelp (this screen).\n"
        exit 0;;
    n) NUMERIC="yes";;
    esac
done


if [ "$VALUE" -gt 69 ]; then
	ICON=""
elif [ "$VALUE" -gt 39 ] && [ "$VALUE" -lt 70 ]; then
	ICON=""
elif [ "$VALUE" -gt 9 ] && [ "$VALUE" -lt 40 ]; then
	ICON=""
else
	ICON=""
fi

if [ "$STATE" == "Full" -o "$VALUE" == "100" ]; then
	ICON=""
	SIGN="±"
elif [ "$STATE" == "Charging" ]; then
	SIGN="+"
elif [ "$STATE" == "Discharging" ]; then
	SIGN="-"
else
	SIGN="±"
fi

if [ "$NUMERIC" == "yes" ];
    then echo $VALUE$SIGN
elif [ "$NUMERIC" == "no" ];
    then echo $ICON $VALUE$SIGN
fi
