#!/bin/sh
panel_clock()
{
    echo  "⮖" $(clock -f '%I:%M')
}

panel_battery()
{
        batStats=$(acpi --battery | cut -d' ' -f3 | sed 's/,//')
        batPower=$(acpi --battery | cut -d' ' -f4 | sed 's/%,//')
        if [ "$batStats" == "Full" ] || [ "$batStats" == "Charging" -a "$batPower" == "100" ]
        then
                echo "\f9⮎ AC"
        elif [ "$batStats" == "Charging" ]
        then
                echo "\f9⮒" $batPower
        elif [ "$batStats" == "Discharging" ]
        then
		    if [ "$batPower" -gt 33 ]
		    then
                echo "⮏"
		    elif [ "$batPower" -lt 34 ] && [ "$batPower" -gt 10 ]
		    then
                echo "\f3⮑"
            else
                echo "\f1⮐"
            fi
            echo $batPower
        else    echo "\f8..."
        fi
}

panel_sigStrength()
{
        signalStrength=$(cat /proc/net/wireless | awk 'NR==3 { print $3}' | sed 's/\.//')

        if [ "$signalStrength" -gt 64 ]
        then
                echo "\f7‗▬▪▮"
        elif [ "$signalStrength" -lt 65 ] && [ "$signalStrength" -gt 39 ]
        then
                echo "\f7‗▬▪\f8▮\f7"
        elif [ "$signalStrength" -lt 40 ]
        then
                echo "\f7‗▬\f8▪▮\f7"
        else
                echo "\f8‗▬▪▮ X"
        fi
}


panel_essid()
{       
        echo $(panel_sigStrength) $(essid -w wlp1s0) "\f7 "
}

panel_volume()
{
        volStatus=$(amixer get Master | tail -n 1 | cut -d '[' -f 4 | sed 's/].*//g')
        volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/\%].*//g')
        headphone=$(amixer -c 0 contents | grep 15 -A 2 | awk 'NR==3 { print $2 }' | cut -d '=' -f 2)

        if [ "$volStatus" == "on" ] && [ "$headphone" == "off" ];
                then icon="\f7 ⮞"
        elif [ "$volStatus" == "on" ] && [ "$headphone" == "on" ];
                then icon="\f7 ⮜"
        elif [ "$volStatus" == "off" ] && [ "$headphone" == "on" ];
                then icon="\f1 ⮜"
        elif [ "$volStatus" == "off" ] && [ "$headphone" == "off" ];
                then icon="\f1 ⮝"
        #else icon="\f1 ⮝"
        fi

        if [ "$volStatus" == "on" ]
            then echo "$icon" "\f7"$volLevel
        else echo "$icon" "\f1"$volLevel
        fi
}