#!/bin/sh

signalStrength=$(cat /proc/net/wireless | awk 'NR==3 { print $3}' | sed 's/\.//')
netID=$(essid -w wlp1s0)

if [ "$signalStrength" -gt 40 ] || [ "$signalStrength" -lt 41 ]
then
	notify-send "Wifi:" "`echo "Connected," $netID "@" $signalStrength"%"`"
else
	notify-send "Wifi:" "`echo "Not Connected"`"
fi